#!/usr/bin/env bash

# To run everyday, use this as a run script:
#
#     #!/bin/sh -e
#     exec snooze -s 1d -t /var/cache/void-update -- /path/to/this/script
#
# see man:snooze(1) for more options

set -e

CLEAN_CACHE=1

is_tty() {
    [[ -t 1 ]]
}

msg() {
    local message="$1"

    if is_tty; then
        echo '***' "$message"
    else
        logger --id="$$" -t "void-update" -p "cron.notice" "$message"
    fi
}

run() {
    if is_tty; then
        "$@"
    else
        #"$@" 1>/dev/null 2> >(logger --id="$$" -t "void-update" -p "cron.err")
        "$@" 1>/dev/null
    fi
}

boot_toggle() {
        msg "Remounting /boot $1..."
        mount /boot -o remount,"$1"
}

#test -z "$(command -v nm-online)" || {
#       msg 'Waiting for network connection...'
#       nm-online -q -x
#}

#test -z "$(command -v connmanctl)" || {
#    msg 'Waiting for network connection...'
#    #connmanctl state | awk '/State/ { print $3 }'
#}

#test -z "$(command -v curl)" || {
#    msg 'Waiting for network connection...'
#    #connmanctl state | awk '/State/ { print $3 }'
#}

check_connection() {
    if ping -W10 -c1 1.1.1.$((RANDOM%9+1)) >/dev/null; then
            msg 'Network connection: online'
    else
            msg 'Network connection: offline'
            exit 1
    fi
}

check_sshd() {
    SSHD_BANNER=$(timeout 5 bash -c 'exec 3<>/dev/tcp/127.0.0.1/22; head -c 20 <&3' 2>/dev/null)
    [[ "$SSHD_BANNER" == SSH-* ]]
}

ensure_sshd() {
    if check_sshd; then
        msg "sshd check: OK ($SSHD_BANNER)"
        return 0
    fi

    msg "sshd check: not responding ('${SSHD_BANNER:-no response}') - restarting"
    run sv restart sshd

    sleep 3

    if check_sshd; then
        msg "sshd check: recovered after restart ($SSHD_BANNER)"
    else
        msg "sshd check: still not responding after restart!"
    fi
}

check_connection

if [[ "$CLEAN_CACHE" == [Yy1] ]]; then
    msg 'Cleaning package cache (xbps-remove -yO)'
    run xbps-remove -yO
fi

msg 'Syncing repositories (xbps-install -S)'
run xbps-install -S

set +e

msg 'Updating packages (xbps-install -yu)'
run xbps-install -yu

if [ "$?" -eq 16 ]; then
    msg 'Updating xbps (xbps-install -yu xbps)'
    run xbps-install -yu xbps

    msg 'Updating packages (xbps-install -yu)'
    run xbps-install -yu
fi

set -e

msg 'Checking sshd status after update'
ensure_sshd

msg 'Removing orphaned packages (xbps-remove -yo)'
run xbps-remove -yo

#msg 'Syncing xlocate (xlocate -S)'
#sudo xlocate -S 1>/dev/null

msg 'Purging old kernels (vkpurge rm all)'
run vkpurge rm all

touch /var/cache/void-update
msg 'Update completed successfully.'

